-- Phase 2 (AMS v1.2): rename the aggregate to Community.
--
-- groups        -> communities
-- group_members -> community_members
-- *.group_id    -> *.community_id
-- role values   -> owner | admin | player   (the stored 'member' becomes
--                  'player'; 'admin' is accepted but not yet granted)
--
-- Behaviour is deliberately unchanged: every policy keeps exactly the rule it
-- had, expressed against the new names. Moving authorization onto
-- community_members.role is Phase 3 - which is why the owner_id and
-- created_by predicates below are copied across untouched for now.
--
-- Renames are in place: no table is dropped, no data is copied.

-- 1) Tables and columns -------------------------------------------------------
alter table public.groups rename to communities;
alter table public.group_members rename to community_members;
alter table public.community_members rename column group_id to community_id;
alter table public.matches rename column group_id to community_id;

alter index public.groups_owner_id_idx rename to communities_owner_id_idx;
alter index public.group_members_user_id_idx rename to community_members_user_id_idx;
alter index public.group_members_group_id_idx
  rename to community_members_community_id_idx;
alter index public.matches_group_id_start_at_idx
  rename to matches_community_id_start_at_idx;

alter trigger groups_set_updated_at on public.communities
  rename to communities_set_updated_at;

-- Constraint names were generated by PostgreSQL and are read from the catalog,
-- not guessed. They only ever surface in error messages, but leaving them
-- saying "group" would be misleading. The role CHECK is not renamed here: it
-- is replaced below to widen the allowed values.
alter table public.communities rename constraint groups_pkey to communities_pkey;
alter table public.communities
  rename constraint groups_join_code_key to communities_join_code_key;
alter table public.communities
  rename constraint groups_owner_id_fkey to communities_owner_id_fkey;
alter table public.communities
  rename constraint groups_name_check to communities_name_check;
alter table public.communities
  rename constraint groups_description_check to communities_description_check;

alter table public.community_members
  rename constraint group_members_pkey to community_members_pkey;
alter table public.community_members
  rename constraint group_members_group_id_user_id_key
  to community_members_community_id_user_id_key;
alter table public.community_members
  rename constraint group_members_group_id_fkey
  to community_members_community_id_fkey;
alter table public.community_members
  rename constraint group_members_user_id_fkey to community_members_user_id_fkey;

alter table public.matches
  rename constraint matches_group_id_fkey to matches_community_id_fkey;

-- 2) Role vocabulary ----------------------------------------------------------
-- The delete policy tests the stored value, so it is dropped first and
-- recreated in step 4 with the new value.
drop policy if exists "group_members_delete_self" on public.community_members;

alter table public.community_members
  drop constraint if exists group_members_role_check;
update public.community_members set role = 'player' where role = 'member';
alter table public.community_members
  add constraint community_members_role_check
  check (role in ('owner', 'admin', 'player'));
alter table public.community_members alter column role set default 'player';

-- 3) Membership helpers -------------------------------------------------------
create or replace function public.is_community_member(
  p_community_id uuid,
  p_user_id uuid
)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from community_members
    where community_id = p_community_id
      and user_id = p_user_id
  );
$$;

create or replace function public.is_match_community_member(
  p_match_id uuid,
  p_user_id uuid
)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from matches m
    join community_members cm on cm.community_id = m.community_id
    where m.id = p_match_id
      and cm.user_id = p_user_id
  );
$$;

revoke execute on function public.is_community_member(uuid, uuid)
  from anon, public;
revoke execute on function public.is_match_community_member(uuid, uuid)
  from anon, public;
grant execute on function public.is_community_member(uuid, uuid)
  to authenticated;
grant execute on function public.is_match_community_member(uuid, uuid)
  to authenticated;

-- 4) Policies: same rules, new names ------------------------------------------
drop policy if exists "groups_select_visible" on public.communities;
create policy "communities_select_visible"
  on public.communities
  for select
  to authenticated
  using (
    is_active
    and (
      not is_private
      or owner_id = auth.uid()
      or public.is_community_member(id, auth.uid())
    )
  );

drop policy if exists "groups_update_owner" on public.communities;
create policy "communities_update_owner"
  on public.communities
  for update
  to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

drop policy if exists "group_members_select_same_group" on public.community_members;
create policy "community_members_select_same_community"
  on public.community_members
  for select
  to authenticated
  using (public.is_community_member(community_id, auth.uid()));

create policy "community_members_delete_self"
  on public.community_members
  for delete
  to authenticated
  using (user_id = auth.uid() and role = 'player');

drop policy if exists "matches_select_group_members" on public.matches;
create policy "matches_select_community_members"
  on public.matches
  for select
  to authenticated
  using (public.is_community_member(community_id, auth.uid()));

drop policy if exists "matches_insert_group_members" on public.matches;
create policy "matches_insert_community_members"
  on public.matches
  for insert
  to authenticated
  with check (
    created_by = auth.uid()
    and public.is_community_member(community_id, auth.uid())
  );

drop policy if exists "match_registrations_select_group_members"
  on public.match_registrations;
create policy "match_registrations_select_community_members"
  on public.match_registrations
  for select
  to authenticated
  using (public.is_match_community_member(match_id, auth.uid()));

-- 5) Community RPCs -----------------------------------------------------------
create or replace function public.create_community(
  p_name text,
  p_description text,
  p_is_private boolean
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_community_id uuid;
begin
  if auth.uid() is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  insert into communities (owner_id, name, description, is_private)
  values (auth.uid(), trim(p_name), p_description, p_is_private)
  returning id into v_community_id;

  insert into community_members (community_id, user_id, role)
  values (v_community_id, auth.uid(), 'owner');

  return v_community_id;
end;
$$;

create or replace function public.join_community_by_code(p_code text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_community_id uuid;
begin
  if auth.uid() is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  select id into v_community_id
  from communities
  where join_code = upper(trim(p_code))
    and is_active;

  if v_community_id is null then
    raise exception 'COMMUNITY_NOT_FOUND';
  end if;

  if is_community_member(v_community_id, auth.uid()) then
    raise exception 'ALREADY_MEMBER';
  end if;

  insert into community_members (community_id, user_id, role)
  values (v_community_id, auth.uid(), 'player');

  return v_community_id;
end;
$$;

revoke execute on function public.create_community(text, text, boolean)
  from anon, public;
revoke execute on function public.join_community_by_code(text)
  from anon, public;
grant execute on function public.create_community(text, text, boolean)
  to authenticated;
grant execute on function public.join_community_by_code(text)
  to authenticated;

-- 6) register_for_match: same logic, community names --------------------------
-- Only the membership check and the column reference change; the lock order,
-- overlap rule, seat allocation and capacity rules are untouched.
create or replace function public.register_for_match(p_match_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_match matches%rowtype;
  v_total int;
  v_confirmed int;
  v_status text;
  v_order int;
begin
  if auth.uid() is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  select * into v_match from matches where id = p_match_id for update;
  if not found then
    raise exception 'MATCH_NOT_FOUND';
  end if;

  perform 1 from users where id = auth.uid() for update;

  if v_match.status = 'completed' or v_match.end_at <= now() then
    raise exception 'MATCH_CLOSED';
  end if;
  if v_match.start_at <= now() then
    raise exception 'MATCH_LOCKED';
  end if;

  if not is_community_member(v_match.community_id, auth.uid()) then
    raise exception 'NOT_COMMUNITY_MEMBER';
  end if;

  if exists (
    select 1 from match_registrations
    where match_id = p_match_id and user_id = auth.uid()
  ) then
    raise exception 'ALREADY_REGISTERED';
  end if;

  select count(*) into v_total
  from match_registrations where match_id = p_match_id;
  if v_total >= v_match.max_registration then
    raise exception 'REGISTRATION_CLOSED';
  end if;

  if exists (
    select 1
    from match_registrations r
    join matches m on m.id = r.match_id
    where r.user_id = auth.uid()
      and m.status in ('open', 'full')
      and m.end_at > now()
      and m.start_at < v_match.end_at
      and m.end_at > v_match.start_at
  ) then
    raise exception 'OVERLAPPING_MATCH';
  end if;

  select count(*) into v_confirmed
  from match_registrations
  where match_id = p_match_id and status = 'confirmed';

  v_status := case
    when v_confirmed < v_match.starting_players then 'confirmed'
    else 'reserve'
  end;

  select coalesce(max(registration_order), 0) + 1 into v_order
  from match_registrations where match_id = p_match_id;

  insert into match_registrations (match_id, user_id, status, registration_order)
  values (p_match_id, auth.uid(), v_status, v_order);

  perform recompute_match_status(p_match_id);
  return v_status;
end;
$$;

-- 7) Retire the superseded functions ------------------------------------------
-- Nothing references these once the policies and RPCs above are in place.
drop function if exists public.create_group(text, text, boolean);
drop function if exists public.join_group_by_code(text);
drop function if exists public.is_group_member(uuid, uuid);
drop function if exists public.is_match_group_member(uuid, uuid);
