-- Wave 2: Data Integrity
-- Additive evidence capture only. No historical backfill.

create table public.match_registration_events (
  event_no bigint generated by default as identity primary key,
  registration_id uuid not null,
  match_id uuid not null,
  community_id uuid,
  user_id uuid not null,
  actor_user_id uuid,
  operation text not null
    check (operation in ('created', 'status_changed', 'deleted')),
  from_status text
    check (from_status is null or from_status in ('confirmed', 'reserve')),
  to_status text
    check (to_status is null or to_status in ('confirmed', 'reserve')),
  match_was_completed boolean,
  occurred_at timestamptz not null default now()
);

create index match_registration_events_community_time_idx
  on public.match_registration_events (community_id, occurred_at desc);
create index match_registration_events_match_time_idx
  on public.match_registration_events (match_id, occurred_at desc);
create index match_registration_events_user_time_idx
  on public.match_registration_events (user_id, occurred_at desc);

alter table public.match_registration_events enable row level security;
revoke all on table public.match_registration_events from anon, authenticated;
revoke all on sequence public.match_registration_events_event_no_seq
  from anon, authenticated;
grant select on table public.match_registration_events to service_role;


create table public.community_membership_events (
  event_no bigint generated by default as identity primary key,
  membership_id uuid not null,
  community_id uuid not null,
  user_id uuid not null,
  actor_user_id uuid,
  operation text not null
    check (operation in ('joined', 'role_changed', 'deleted')),
  from_role text
    check (from_role is null or from_role in ('owner', 'admin', 'player')),
  to_role text
    check (to_role is null or to_role in ('owner', 'admin', 'player')),
  occurred_at timestamptz not null default now()
);

create index community_membership_events_community_time_idx
  on public.community_membership_events (community_id, occurred_at desc);
create index community_membership_events_user_time_idx
  on public.community_membership_events (user_id, occurred_at desc);

alter table public.community_membership_events enable row level security;
revoke all on table public.community_membership_events from anon, authenticated;
revoke all on sequence public.community_membership_events_event_no_seq
  from anon, authenticated;
grant select on table public.community_membership_events to service_role;


create table public.match_participation_state (
  match_id uuid primary key
    references public.matches(id) on delete cascade,
  lineup_revision bigint not null default 0
    check (lineup_revision >= 0),
  confirmed_revision bigint
    check (
      confirmed_revision is null
      or (
        confirmed_revision >= 0
        and confirmed_revision <= lineup_revision
      )
    ),
  confirmed_at timestamptz,
  confirmed_by uuid,
  constraint match_participation_confirmation_shape check (
    (confirmed_revision is null and confirmed_at is null and confirmed_by is null)
    or
    (confirmed_revision is not null and confirmed_at is not null and confirmed_by is not null)
  )
);

alter table public.match_participation_state enable row level security;
revoke all on table public.match_participation_state from anon, authenticated;
grant select on table public.match_participation_state to service_role;


create or replace function public.capture_match_registration_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_match_id uuid;
  v_user_id uuid;
  v_registration_id uuid;
  v_community_id uuid;
  v_completed boolean;
  v_from_status text;
  v_to_status text;
  v_operation text;
begin
  if tg_op = 'INSERT' then
    if new.user_id is null then return new; end if;
    v_match_id := new.match_id;
    v_user_id := new.user_id;
    v_registration_id := new.id;
    v_operation := 'created';
    v_from_status := null;
    v_to_status := new.status;
  elsif tg_op = 'UPDATE' then
    if new.user_id is null or new.status is not distinct from old.status then
      return new;
    end if;
    v_match_id := new.match_id;
    v_user_id := new.user_id;
    v_registration_id := new.id;
    v_operation := 'status_changed';
    v_from_status := old.status;
    v_to_status := new.status;
  else
    if old.user_id is null then return old; end if;
    v_match_id := old.match_id;
    v_user_id := old.user_id;
    v_registration_id := old.id;
    v_operation := 'deleted';
    v_from_status := old.status;
    v_to_status := null;
  end if;

  select
    m.community_id,
    (m.status = 'completed' or m.end_at <= now())
  into v_community_id, v_completed
  from public.matches m
  where m.id = v_match_id;

  insert into public.match_registration_events (
    registration_id,
    match_id,
    community_id,
    user_id,
    actor_user_id,
    operation,
    from_status,
    to_status,
    match_was_completed
  )
  values (
    v_registration_id,
    v_match_id,
    v_community_id,
    v_user_id,
    auth.uid(),
    v_operation,
    v_from_status,
    v_to_status,
    v_completed
  );

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

revoke execute on function public.capture_match_registration_event()
  from public, anon, authenticated;


create trigger match_registrations_capture_lifecycle
after insert or update or delete on public.match_registrations
for each row execute function public.capture_match_registration_event();


create or replace function public.capture_community_membership_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.community_membership_events (
      membership_id,
      community_id,
      user_id,
      actor_user_id,
      operation,
      from_role,
      to_role
    )
    values (
      new.id,
      new.community_id,
      new.user_id,
      auth.uid(),
      'joined',
      null,
      new.role
    );
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if new.role is not distinct from old.role then return new; end if;
    insert into public.community_membership_events (
      membership_id,
      community_id,
      user_id,
      actor_user_id,
      operation,
      from_role,
      to_role
    )
    values (
      new.id,
      new.community_id,
      new.user_id,
      auth.uid(),
      'role_changed',
      old.role,
      new.role
    );
    return new;
  end if;

  insert into public.community_membership_events (
    membership_id,
    community_id,
    user_id,
    actor_user_id,
    operation,
    from_role,
    to_role
  )
  values (
    old.id,
    old.community_id,
    old.user_id,
    auth.uid(),
    'deleted',
    old.role,
    null
  );
  return old;
end;
$$;

revoke execute on function public.capture_community_membership_event()
  from public, anon, authenticated;


create trigger community_members_capture_lifecycle
after insert or update or delete on public.community_members
for each row execute function public.capture_community_membership_event();


create or replace function public.advance_match_participation_revision()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_match_id uuid;
  v_community_id uuid;
  v_status text;
  v_end_at timestamptz;
  v_revision bigint;
  v_actor uuid;
begin
  v_match_id := case when tg_op = 'DELETE' then old.match_id else new.match_id end;

  select m.community_id, m.status, m.end_at
  into v_community_id, v_status, v_end_at
  from public.matches m
  where m.id = v_match_id;

  if not found then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  insert into public.match_participation_state (
    match_id,
    lineup_revision
  )
  values (v_match_id, 1)
  on conflict (match_id) do update
    set lineup_revision =
      public.match_participation_state.lineup_revision + 1
  returning lineup_revision into v_revision;

  v_actor := auth.uid();

  if (v_status = 'completed' or v_end_at <= now())
     and v_actor is not null
     and public.has_active_community_role(
       v_community_id,
       v_actor,
       'admin'
     )
  then
    update public.match_participation_state
    set confirmed_revision = v_revision,
        confirmed_at = now(),
        confirmed_by = v_actor
    where match_id = v_match_id;
  end if;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

revoke execute on function public.advance_match_participation_revision()
  from public, anon, authenticated;


create trigger match_team_assignments_advance_participation_revision
after insert or update or delete on public.match_team_assignments
for each row execute function public.advance_match_participation_revision();


create or replace function public.confirm_match_participation(
  p_match_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_match public.matches%rowtype;
begin
  if auth.uid() is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  if not public.is_current_user_active() then
    raise exception 'ACCOUNT_SUSPENDED';
  end if;

  select *
  into v_match
  from public.matches
  where id = p_match_id
  for update;

  if not found then
    raise exception 'MATCH_NOT_FOUND';
  end if;

  if not exists (
    select 1
    from public.communities c
    where c.id = v_match.community_id
      and c.is_active
  ) then
    raise exception 'COMMUNITY_INACTIVE';
  end if;

  if not public.has_active_community_role(
    v_match.community_id,
    auth.uid(),
    'admin'
  ) then
    raise exception 'NOT_AUTHORIZED';
  end if;

  if v_match.status <> 'completed'
     and v_match.end_at > now()
  then
    raise exception 'MATCH_NOT_COMPLETED';
  end if;

  if not exists (
    select 1
    from public.match_team_assignments a
    where a.match_id = p_match_id
  ) then
    raise exception 'LINEUP_REQUIRED';
  end if;

  insert into public.match_participation_state (
    match_id,
    lineup_revision
  )
  values (p_match_id, 1)
  on conflict (match_id) do nothing;

  update public.match_participation_state
  set confirmed_revision = lineup_revision,
      confirmed_at = now(),
      confirmed_by = auth.uid()
  where match_id = p_match_id;
end;
$$;

comment on function public.confirm_match_participation(uuid) is
  'Wave 2 organizer confirmation that the current completed lineup is the factual participation record. Does not alter lineup, result, ratings or statistics.';

revoke execute on function public.confirm_match_participation(uuid)
  from public, anon;
grant execute on function public.confirm_match_participation(uuid)
  to authenticated, service_role;


comment on table public.match_registration_events is
  'Wave 2 append-only account registration lifecycle evidence. No historical backfill.';
comment on table public.community_membership_events is
  'Wave 2 append-only membership lifecycle evidence. No historical backfill.';
comment on table public.match_participation_state is
  'Wave 2 mutable confirmation state for the authoritative lineup revision; participants remain in match_team_assignments.';
